# Generated by Django 3.2 on 2021-04-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('expires', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.item')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.trip')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Shrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('method', models.CharField(choices=[('E', 'Expired'), ('U', 'Used in cooking')], default='U', max_length=1)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.supply')),
            ],
        ),
    ]
