# Generated by Django 3.2 on 2021-04-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shrink_supply_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='recipes.source'),
            preserve_default=False,
        ),
    ]
