# Generated by Django 3.2 on 2021-04-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210425_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shrink',
            new_name='Usage',
        ),
    ]
