# Generated by Django 3.2 on 2021-04-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='recipes.item'),
            preserve_default=False,
        ),
    ]
