# Generated by Django 3.2 on 2021-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_shrink_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
